### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by Azkalaak** [hashhar/rEFInd-theme#1]
in your theme.conf and theme_dark.conf, you have the following problem: your path is invalid, you should change all rEFInd-minimal to rEFInd-theme to make it work.

**Comment by hashhar** [comment]
@Azkalaak A PR would be welcome. Thanks for catching this. I had it always locally cloned as rEFInd-minimal so it worked.

**Comment by Azkalaak** [comment]
i'm a noob at creating a pull request, I followed a tutorial but could not managed to do one :/
could you please tell me how to do one?

**Comment by Azkalaak** [comment]
nevermind, found it
